# Generated by Django 3.2.7 on 2021-09-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='image',
            field=models.ImageField(upload_to='furniture_images/'),
        ),
    ]
